server:
  port: 9999
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      fail_on_empty_beans: false
    default-property-inclusion: non_empty
    deserialization:
      fail_on_unknown_properties: false
  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter: pageSize
        default-page-size: 50
        max-page-size: 2000
      sort:
        sort-parameter: sort
  elasticsearch:
    uris:
      - http://localhost:9200

logging:
  level:
    cn.houtaroy.java.samples.elasticsearch: DEBUG
  file:
    name: elasticsearch.log